---
- hosts: [localhost]
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - utils
    - brave
    - spotify
    - docker
  # tasks:
  #   - include_role:
  #       name: docker
  #     tags:
  #       - docker
