---
# WIP (TODO: have this config driven instead of hardcoded, templatize the desktop entry, blah, etc)
- name: create installation directory
  file:
    state: directory
    path: '/opt/firefox-dev'

- name: fetch and unpack archive
  unarchive:
    src: 'https://download-installer.cdn.mozilla.net/pub/devedition/releases/95.0b12/linux-x86_64/en-US/firefox-95.0b12.tar.bz2'
    dest: /opt/firefox-dev
    remote_src: yes

- name: ln opt/firefox -> usr/local/bin
  become: true
  shell: ln -s /opt/firefox-dev/firefox /usr/local/bin/firefox-dev

- name: create .desktop entry for firefox
  become: true
  copy: src=files/firefox-developer.desktop dest=/usr/share/applications/firefox-developer.desktop
