---
- name: fetch joplin installation script
  get_url:
    url: https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
    dest: ~/downloads/joplin-install.sh
    mode: '700'
  tags:
    - apps
    - joplin

- name: run joplin installation script
  shell: ~/downloads/joplin-install.sh
  args:
    executable: /bin/bash
  tags:
    - apps
    - joplin
