---
# easier installs
- name: add keys for signal, element, spotterfy, vscode
  become: true
  apt_key:
    url: '{{item}}'
    state: present
  loop:
    - 'https://download.spotify.com/debian/pubkey_0D811D58.gpg'
    - 'https://updates.signal.org/desktop/apt/keys.asc'
    - 'https://packages.microsoft.com/keys/microsoft.asc'
  tags:
    - apps

- name: enable extra repos
  become: true
  apt_repository: filename='{{item.file}}' repo='{{item.repo}}' state=present
  loop:
    - { file: 'signal', repo: 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' }
    - { file: 'spotify', repo: 'deb http://repository.spotify.com stable non-free' }
    - { file: 'vscode', repo: 'deb https://packages.microsoft.com/repos/vscode stable main' }
  notify: [ update apt ]
  tags:
    - apps

- name: install third party apps and stuff
  become: true
  apt:
    state: latest
    name: 
      - code
      - nextcloud-desktop
      - signal-desktop
      - spotify-client
      - tmux
      - vim-gtk3
  tags:
    - apps

- name: dot files
  copy: src=files/{{ item.src }} dest={{ item.dest }}
  with_items:
    - {'src': 'tmux.conf', 'dest': '$HOME/.tmux.conf'}
    - {'src': 'vimrc', 'dest': '$HOME/.vimrc'}
    - {'src': 'inputrc', 'dest': '$HOME/.inputrc'}
    - {'src': 'bashrc', 'dest': '$HOME/.bashrc'}
  tags:
    - apps

# hopefully can remove this section in the future
- name: dl setup
  file:
    state: directory
    path: ~/downloads/rebuildme
  tags:
    - appindicator

- name: fetch desktop apps that need to be rebuilt
  get_url:
    url: '{{ item }}'
    dest: ~/downloads/rebuildme
  with_items:
    - 'https://github.com/keeweb/keeweb/releases/download/v1.18.7/KeeWeb-1.18.7.linux.x64.deb'
    - 'https://dl.discordapp.net/apps/linux/0.0.16/discord-0.0.16.deb'
  tags:
    - appindicator

- name: rebuild packages that need libappindicator
  script: scripts/replace-appindicator --cleanup {{ item }}
  loop: "{{ lookup('fileglob','~/downloads/rebuildme/*.deb',wantlist=true) | reject('search','-fixed') | list }}"
  tags:
    - appindicator

- name: install rebuilt packages
  become: true
  apt:
    deb: '{{ item }}'
  with_fileglob: '~/downloads/rebuildme/*-fixed.deb'
  tags:
    - appindicator

# joplin
- name: install joplin
  include_tasks: joplin.yml
  tags:
    - apps
    - joplin

- name: Add apps to favorites
  shell: "gsettings set org.gnome.shell favorite-apps \"['firefox-esr.desktop', 'spotify.desktop', 'org.gnome.Terminal.desktop', 'code.desktop', 'appimagekit-joplin.desktop', 'keeweb.desktop', 'signal-desktop.desktop', 'discord.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.gedit.desktop']\""
  tags:
    - apps
