---
- name: config files
  copy: src=files/{{ item.src }} dest={{ item.dest }}
  with_items:
    - {'src': 'tmux.conf', 'dest': '$HOME/.tmux.conf'}
    - {'src': 'vimrc', 'dest': '$HOME/.vimrc'}
    - {'src': 'inputrc', 'dest': '$HOME/.inputrc'}

